### ISSUE TITLE
ethmonitor: review behaviour if Options.LogTopics is defined

### ISSUE THREAD

**Issue by attente** [0xsequence/ethkit#55]
https://github.com/0xsequence/ethkit/blob/7d9af4e211c25a5533b8e66195706ae1602fe22f/ethmonitor/ethmonitor.go#L324-L347

I haven't tried this, but I think if topics are specified, then it's possible to receive no logs, while the logs bloom filter is non-zero. This means the block is never considered backfilled and causes the monitor to hang if logs are requested.

**Comment by 0xbsa** [comment]
I'm facing this exact issue. My `topics` slice is non-empty and the monitor hangs after encountering a block without any matching logs (as per `topics` filter)

**Comment by 0xbsa** [comment]
Why is this check required at all?
https://github.com/0xsequence/ethkit/blob/7d9af4e211c25a5533b8e66195706ae1602fe22f/ethmonitor/ethmonitor.go#L337

**Comment by pkieltyka** [comment]
outdated
