### ISSUE TITLE
Possible bug in ethmonitor/bootstrap

### ISSUE THREAD

**Issue by 0xbsa** [0xsequence/ethkit#77]
https://github.com/0xsequence/ethkit/blob/da313b899ccc328208f1eb585ba5532bfbce4aa4/ethmonitor/bootstrap.go#L49

Above line should be:
```go
blocks = blocks[len(blocks)-c.retentionLimit-1:] 
```

updated `len(blocks)` after above change:
```
updatedLength = len(blocks)-1 - (len(blocks)-c.retentionLimit-1)
= c.retentionLimit
```
---
for example, consider `blocks` to be slice with `length=150` and `c.retentionLimit=100` then current code will do this:
```go
blocks = blocks[99:] //blocks will end up with length = 50 (=len(blocks)-retentionLimit)
```
with change:
```go
blocks = blocks[49:] //blocks will have length = 100 (=retentionLimit)
```

**Comment by pkieltyka** [comment]
thx for the report, will check it out. Which project are you with? :)

**Comment by 0xbsa** [comment]
Thanks for the quick fix 🙌 

> Which project are you with? :)

None :) just a solo dev.

**Comment by pkieltyka** [comment]
Nice :) lmk if you’d like to chat about a gig sometime. My Twitter DM @peterk is open

**Comment by 0xbsa** [comment]
Cool. Thank you
